import logging
import uuid
from abc import ABC, abstractmethod
from typing import Optional, Sequence

from app.models.domain import AnalyticsReport
from app.repositories.bigquery_repository import AnalyticsReportRepositoryInterface
from app.repositories.storage_repository import StorageRepositoryInterface
from app.schemas.reports import ReportCreate
from app.services.base import BaseService

logger = logging.getLogger("app.services.reports")


class ReportsServiceInterface(BaseService, ABC):
    """Interface for compiling analytics datasets and exporting files."""

    @abstractmethod
    def generate_report(self, report_in: ReportCreate, user_id: str) -> AnalyticsReport:
        """Runs the query, uploads output file to GCS, and saves report records."""
        pass

    @abstractmethod
    def get_report(self, report_id: str) -> Optional[AnalyticsReport]:
        """Fetches a generated report by ID."""
        pass

    @abstractmethod
    def list_reports(self, user_id: str) -> Sequence[AnalyticsReport]:
        """Lists reports generated by a specific user."""
        pass


class ReportsService(ReportsServiceInterface):
    """Concrete implementation of ReportsService."""

    def __init__(
        self,
        report_repo: AnalyticsReportRepositoryInterface,
        storage_repo: StorageRepositoryInterface,
    ) -> None:
        self.report_repo = report_repo
        self.storage_repo = storage_repo

    def generate_report(self, report_in: ReportCreate, user_id: str) -> AnalyticsReport:
        logger.info(f"Generating report '{report_in.title}' for user: {user_id}")
        report_id = f"rep-{uuid.uuid4()}"
        blob_name = f"reports/{user_id}/{report_id}.{report_in.export_format}"

        # In production, we would execute self.bq_manager.execute_query(report_in.query_executed)
        # and parse results into target formats (CSV, JSON, PDF).
        # Here we simulate compiling a dummy dataset string.
        simulated_data = (
            f"Report Title: {report_in.title}\n"
            f"Query: {report_in.query_executed}\n"
            f"Generated By: {user_id}\n"
            f"Data: [Simulated analytical metrics]"
        )

        # Upload file output to storage
        content_type = "text/csv" if report_in.export_format == "csv" else "application/json"
        public_url = self.storage_repo.upload_blob(
            blob_name, simulated_data.encode("utf-8"), content_type=content_type
        )
        gcs_uri = f"gs://{self.storage_repo.bucket_name}/{blob_name}" if hasattr(self.storage_repo, "bucket_name") else f"gs://streamline-data-ingestion/{blob_name}"

        report = AnalyticsReport(
            id=report_id,
            title=report_in.title,
            query_executed=report_in.query_executed,
            export_format=report_in.export_format,
            gcs_uri=gcs_uri,
            created_by=user_id,
        )

        # Save metadata record
        return self.report_repo.save(report)

    def get_report(self, report_id: str) -> Optional[AnalyticsReport]:
        return self.report_repo.get_by_id(report_id)

    def list_reports(self, user_id: str) -> Sequence[AnalyticsReport]:
        return self.report_repo.list_by_user(user_id)

