from typing import Literal, Optional

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Schema representing an individual entry in a conversation thread."""

    role: Literal["user", "model"] = Field(
        ..., description="Role of the message author"
    )
    content: str = Field(..., description="Text content of the message")


class ChatRequest(BaseModel):
    """Request payload containing chat query and conversation history."""

    message: str = Field(..., description="The user query or prompt")
    history: list[ChatMessage] = Field(
        default_factory=list, description="Previous messages in the conversation thread"
    )
    context_dataset_id: Optional[str] = Field(
        None, description="Optional BigQuery dataset key to ground the LLM's answers"
    )


class ChatResponse(BaseModel):
    """Response payload containing assistant's generated response and references."""

    response: str = Field(..., description="Markdown response generated by the model")
    sources: list[str] = Field(
        default_factory=list,
        description="Referenced BigQuery tables, documents, or GCS paths",
    )
    token_usage: int = Field(
        0, description="Approximated tokens consumed in the transaction"
    )
