from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field


class RuleCreate(BaseModel):
    """Payload to register a new decision rule in the intelligence engine."""

    name: str = Field(..., min_length=3, description="Descriptive label for the rule")
    expression: str = Field(..., description="Condition expression syntax to evaluate (e.g. 'input.risk > 0.8')")
    action: str = Field(..., description="Action tag or label to return if expression evaluates true")
    priority: int = Field(default=1, ge=1, description="Precedence sequence (1 represents highest priority)")


class RuleResponse(BaseModel):
    """Response payload detailing registered decision rules."""

    id: str
    name: str
    expression: str
    action: str
    priority: int
    is_active: bool
    created_by: str
    created_at: datetime


class DecisionEvaluationRequest(BaseModel):
    """Payload containing input variables to pass to the decision engine."""

    context: dict[str, Any] = Field(..., description="Dictionary of variables to test rules against")


class DecisionEvaluationResponse(BaseModel):
    """Outcome payload generated by the decision intelligence engine."""

    evaluated_rules_count: int = Field(..., description="Total count of rules checked")
    matched_rules: list[str] = Field(..., description="Identifiers of rules that resolved to True")
    recommended_actions: list[str] = Field(..., description="Calculated actions ordered by priority")
    execution_time_ms: float = Field(..., description="Resolution latency in milliseconds")
