from typing import Any, Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Payload representing a natural language question sent to the chat assistant."""

    message: str = Field(..., description="The user's query or instruction")
    workspace: Optional[str] = Field(
        "default", description="Workspace scope constraint"
    )
    context_override: Optional[dict[str, Any]] = Field(
        None, description="Optional extra parameters"
    )


class ChatResponse(BaseModel):
    """Payload representing the response returned by the chat assistant."""

    response: str = Field(
        ..., description="The plain text or markdown response generated by Gemini"
    )
    confidence: Optional[float] = Field(
        None, description="Confidence metric percentage"
    )
    context_used: dict[str, Any] = Field(
        default_factory=dict, description="Metadata metrics used as context"
    )


class ExplainDecisionRequest(BaseModel):
    """Payload to trigger decision explanation."""

    decision_id: str = Field(
        ..., description="Unique UUID of the Decision object to explain"
    )


class ExplainDecisionResponse(BaseModel):
    """Payload representing the business explanation details returned by Gemini."""

    decision_id: str
    explanation: str = Field(..., description="Executive-level narrative explanation")
    action_plan: str = Field(
        ..., description="Actionable checklist based on recommendations"
    )


class ExecutiveSummaryResponse(BaseModel):
    """Payload representing the generated executive health report."""

    business_health_summary: str = Field(
        ..., description="Summary of overall business performance indicators"
    )
    top_risks: list[str] = Field(
        default_factory=list,
        description="Top risks based on active Critical and High decisions",
    )
    top_opportunities: list[str] = Field(
        default_factory=list, description="Key opportunities based on high performers"
    )
    recommended_actions: list[str] = Field(
        default_factory=list, description="Immediate recommended priority tasks"
    )
    generation_time_ms: float = Field(
        ..., description="Total processing time in milliseconds"
    )


class TrendExplanationRequest(BaseModel):
    """Payload representing datasets to explain trends on."""

    trend_type: str = Field(
        ..., description="Type of trend: 'revenue', 'inventory', or 'expense'"
    )
    raw_data_summary: dict[str, Any] = Field(
        ..., description="Summarized values of time-series datapoints"
    )


class TrendExplanationResponse(BaseModel):
    """Payload representing the trend explanation details returned by Gemini."""

    trend_type: str
    explanation: str = Field(..., description="Plain language trend summary")
    implications: str = Field(
        ..., description="Operational implications of the current trend trajectory"
    )
