import logging
from abc import ABC, abstractmethod
from typing import Optional, Sequence

from app.database.bigquery import BigQueryManager
from app.models.domain import AnalyticsReport, DecisionRule, SimulationScenario
from app.repositories.base import BaseRepository

logger = logging.getLogger("app.repositories.bigquery")


class DecisionRuleRepositoryInterface(BaseRepository[DecisionRule], ABC):
    """Interface for retrieving and managing Decision Rules."""

    @abstractmethod
    def list_active(self) -> Sequence[DecisionRule]:
        """Retrieves only active rules."""
        pass


class SimulationScenarioRepositoryInterface(BaseRepository[SimulationScenario], ABC):
    """Interface for retrieving and managing Simulation Scenarios."""

    @abstractmethod
    def get_by_status(self, status: str) -> Sequence[SimulationScenario]:
        """Retrieves scenarios matching a specific status."""
        pass


class AnalyticsReportRepositoryInterface(BaseRepository[AnalyticsReport], ABC):
    """Interface for retrieving and managing Analytics Reports."""

    @abstractmethod
    def list_by_user(self, user_id: str) -> Sequence[AnalyticsReport]:
        """Retrieves reports generated by a specific user."""
        pass


# Concrete BigQuery implementations
class BigQueryDecisionRuleRepository(DecisionRuleRepositoryInterface):
    """BigQuery implementation of the Decision Rule repository."""

    def __init__(self, bq_manager: BigQueryManager) -> None:
        self.bq_manager = bq_manager
        # Table reference setup
        self.dataset = "streamline_metadata"
        self.table = "decision_rules"

    def get_by_id(self, id: str) -> Optional[DecisionRule]:
        logger.info(f"Fetching decision rule {id} from BigQuery")
        query = f"SELECT * FROM `{self.dataset}.{self.table}` WHERE id = '{id}' LIMIT 1"
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                return DecisionRule.model_validate(dict(row))
        except Exception as e:
            logger.error(f"Error getting rule by ID: {str(e)}")
        return None

    def list_all(self) -> Sequence[DecisionRule]:
        logger.info("Listing all decision rules from BigQuery")
        query = f"SELECT * FROM `{self.dataset}.{self.table}` ORDER BY priority ASC"
        rules = []
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                rules.append(DecisionRule.model_validate(dict(row)))
        except Exception as e:
            logger.error(f"Error listing all rules: {str(e)}")
        return rules

    def list_active(self) -> Sequence[DecisionRule]:
        logger.info("Listing active decision rules from BigQuery")
        query = f"SELECT * FROM `{self.dataset}.{self.table}` WHERE is_active = TRUE ORDER BY priority ASC"
        rules = []
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                rules.append(DecisionRule.model_validate(dict(row)))
        except Exception as e:
            logger.error(f"Error listing active rules: {str(e)}")
        return rules

    def save(self, entity: DecisionRule) -> DecisionRule:
        logger.info(f"Saving decision rule {entity.id} to BigQuery")
        row = [entity.model_dump(mode="json")]
        errors = self.bq_manager.insert_rows_json(self.dataset, self.table, row)
        if errors:
            raise RuntimeError(f"Failed to insert decision rule: {errors}")
        return entity

    def delete_by_id(self, id: str) -> None:
        logger.info(f"Deleting decision rule {id} from BigQuery")
        query = f"DELETE FROM `{self.dataset}.{self.table}` WHERE id = '{id}'"
        self.bq_manager.execute_query(query)


class BigQuerySimulationScenarioRepository(SimulationScenarioRepositoryInterface):
    """BigQuery implementation of the Simulation Scenario repository."""

    def __init__(self, bq_manager: BigQueryManager) -> None:
        self.bq_manager = bq_manager
        self.dataset = "streamline_metadata"
        self.table = "simulation_scenarios"

    def get_by_id(self, id: str) -> Optional[SimulationScenario]:
        logger.info(f"Fetching simulation scenario {id} from BigQuery")
        query = f"SELECT * FROM `{self.dataset}.{self.table}` WHERE id = '{id}' LIMIT 1"
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                return SimulationScenario.model_validate(dict(row))
        except Exception as e:
            logger.error(f"Error getting scenario by ID: {str(e)}")
        return None

    def list_all(self) -> Sequence[SimulationScenario]:
        logger.info("Listing all simulation scenarios from BigQuery")
        query = f"SELECT * FROM `{self.dataset}.{self.table}` ORDER BY created_at DESC"
        scenarios = []
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                scenarios.append(SimulationScenario.model_validate(dict(row)))
        except Exception as e:
            logger.error(f"Error listing scenarios: {str(e)}")
        return scenarios

    def get_by_status(self, status: str) -> Sequence[SimulationScenario]:
        logger.info(f"Listing simulation scenarios with status {status}")
        query = f"SELECT * FROM `{self.dataset}.{self.table}` WHERE status = '{status}'"
        scenarios = []
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                scenarios.append(SimulationScenario.model_validate(dict(row)))
        except Exception as e:
            logger.error(f"Error listing scenarios by status: {str(e)}")
        return scenarios

    def save(self, entity: SimulationScenario) -> SimulationScenario:
        logger.info(f"Saving simulation scenario {entity.id} to BigQuery")
        row = [entity.model_dump(mode="json")]
        errors = self.bq_manager.insert_rows_json(self.dataset, self.table, row)
        if errors:
            raise RuntimeError(f"Failed to insert scenario: {errors}")
        return entity

    def delete_by_id(self, id: str) -> None:
        logger.info(f"Deleting simulation scenario {id} from BigQuery")
        query = f"DELETE FROM `{self.dataset}.{self.table}` WHERE id = '{id}'"
        self.bq_manager.execute_query(query)


class BigQueryAnalyticsReportRepository(AnalyticsReportRepositoryInterface):
    """BigQuery implementation of the Analytics Report repository."""

    def __init__(self, bq_manager: BigQueryManager) -> None:
        self.bq_manager = bq_manager
        self.dataset = "streamline_metadata"
        self.table = "analytics_reports"

    def get_by_id(self, id: str) -> Optional[AnalyticsReport]:
        query = f"SELECT * FROM `{self.dataset}.{self.table}` WHERE id = '{id}' LIMIT 1"
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                return AnalyticsReport.model_validate(dict(row))
        except Exception as e:
            logger.error(f"Error getting report: {str(e)}")
        return None

    def list_all(self) -> Sequence[AnalyticsReport]:
        query = f"SELECT * FROM `{self.dataset}.{self.table}` ORDER BY created_at DESC"
        reports = []
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                reports.append(AnalyticsReport.model_validate(dict(row)))
        except Exception as e:
            logger.error(f"Error listing reports: {str(e)}")
        return reports

    def list_by_user(self, user_id: str) -> Sequence[AnalyticsReport]:
        query = f"SELECT * FROM `{self.dataset}.{self.table}` WHERE created_by = '{user_id}' ORDER BY created_at DESC"
        reports = []
        try:
            results = self.bq_manager.execute_query(query)
            for row in results:
                reports.append(AnalyticsReport.model_validate(dict(row)))
        except Exception as e:
            logger.error(f"Error listing reports by user: {str(e)}")
        return reports

    def save(self, entity: AnalyticsReport) -> AnalyticsReport:
        row = [entity.model_dump(mode="json")]
        errors = self.bq_manager.insert_rows_json(self.dataset, self.table, row)
        if errors:
            raise RuntimeError(f"Failed to insert report metadata: {errors}")
        return entity

    def delete_by_id(self, id: str) -> None:
        query = f"DELETE FROM `{self.dataset}.{self.table}` WHERE id = '{id}'"
        self.bq_manager.execute_query(query)
